### ISSUE TITLE
bbok.vercel.app CORS 에러 수정

### ISSUE THREAD

**Issue by BoBeenLee** [dnd-side-project/dnd-9th-10-backend#38]
## 📌Feature Issue
-  https://bbok.vercel.app/ 도메인도 추가 부탁드립니다.

- ex) https://github.com/dnd-side-project/dnd-9th-10-backend/commit/63083fd6c6acca82624a1330ad4039adbbc27f4f#diff-68aea48a61f2053ac5539ccbcb12ceb4dfbeeda89e3c0f52f53418a73cb7ec79

```
registry.addMapping("/**").allowedOrigins("https://bbok.vercel.app");
```

## 📝To-do
- [x]
## ETC
>

**Comment by D0ri123** [comment]
넵 알겠습니다~!!

**Comment by BoBeenLee** [comment]
해당 이슈도 해결된듯 싶어 클로즈하겠습니다! @D0ri123
